level:
  #等级最大值
  max: 100
  #等级名称
  name: 等级
  #1级需要经验
  a1: 100
  #每级需要的经验增加值
  d: 50

#这里自定义属性
qualities:
  #示例属性1，这里的quality_1就是变量名%quality_1%，建议使用英文以防止奇奇怪怪的问题
  - quality_1:
      #1级需要的经验
      a1: 10
      #每级需要的经验增加值
      d: 10
      #最大等级
      max: 100
      #显示的中文名
      display_name: 魂力
  #示例属性2
  - quality_2:
      a1: 10
      d: 20
      max: 100
      display_name: 体质