name: DouluoLevel
version: '${project.version}'
main: douluolevel.douluolevel.DouluoLevel
api-version: 1.12
authors: [ Ender ]
description: 用于斗罗服务器的等级系统
depend:
  - PlaceholderAPI
  - AttributePlus
  - SkillAPI
  - AttributeAPI

commands:
  leveladmin:
    aliases:
      - la
    description: 用于斗罗等级系统管理的命令
    permission: douluolevel.admin
    permission-message: 你没有使用此命令的权限，请联系管理员咨询
    usage: |
      /leveladmin set level <玩家> <等级> 设置某个玩家的等级
      /leveladmin set quality <玩家> <属性> <等级> 设置某个玩家的某个属性的等级
      /leveladmin set exp_current <玩家> <经验> 设置某个玩家的剩余经验等级(这不会影响到等级)
      /leveladmin set exp_record <玩家> <经验> 设置某个玩家的总经验等级(这会影响到等级)
      /leveladmin purge <玩家> 清除玩家的数据，仅离线可用
      /leveladmin remake <玩家> 重置玩家的数据
      /leveladmin show 显示某个玩家的等级和属性情况
  quality:
    aliases:
      - q
    description: 用于管理玩家属性
    permission: douluolevel.quality
    permission-message: 你没有使用此命令的权限，请联系管理员咨询
    usage: |
      /quality upgrade <属性名> 升级某个属性
      /quality list 列出可升级的属性
  levelmessage:
    aliases:
      - lm
    description: 用于给玩家发送信息
permissions:
  douluolevel.admin:
    description: 管理员用权限
    default: true
  douluolevel.vip:
    default: false
    description: VIP用权限
  douluolevel.quality:
    description: 属性管理权限
    default: true